# Generated by Django 4.0.1 on 2022-07-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_customuser_friends_remove_friend_friend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='first_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='upload/profile_pic'),
        ),
        migrations.AddField(
            model_name='friend',
            name='username',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
    ]
