# Generated by Django 4.0.1 on 2022-07-11 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_friend_email_friend_first_name_friend_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='email',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='username',
        ),
        migrations.AddField(
            model_name='friend',
            name='friend',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
